# Generated by Django 6.0 on 2026-01-02 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrjetSqncmnto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, unique=True, verbose_name='Descrição do Projeto')),
                ('detalhe', models.TextField(blank=True, verbose_name='Detalhe')),
                ('dt_Criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('dt_Atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('dt_Inicio', models.DateField(blank=True, null=True, verbose_name='Data de Início')),
                ('dt_Fim', models.DateField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('status', models.CharField(choices=[('Plnjdo', 'Planejado'), ('EAndmnto', 'Em andamento'), ('Concldo', 'Concluído'), ('Cancldo', 'Cancelado')], default='Plnjdo', max_length=20, verbose_name='Status')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_responsaveis', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Projeto de Sequenciamento',
                'verbose_name_plural': 'Projetos de Sequenciamento',
                'db_table': 'Projeto_Sequenciamento',
                'ordering': ['-dt_Criacao'],
            },
        ),
    ]
