# Generated by Django 6.0 on 2026-01-03 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prjetsqncmnto',
            name='tipo_projeto',
            field=models.CharField(choices=[('TCC', 'Trabalho de Conclusão de Curso'), ('Artigo', 'Artigo Científico'), ('Dissertacao', 'Dissertação'), ('Tese', 'Tese'), ('Estudo', 'Estudo')], default='Estudo', max_length=20, verbose_name='Tipo de Projeto'),
        ),
    ]
