# Generated by Django 6.0 on 2025-12-30 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UfEstados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UfEstados', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Prfl_Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Endereco', models.CharField(max_length=200)),
                ('Numero', models.CharField(default='0', max_length=10)),
                ('Complemento', models.CharField(blank=True, max_length=200, null=True)),
                ('Bairro', models.CharField(max_length=125)),
                ('Referencia', models.CharField(blank=True, max_length=175, null=True)),
                ('urlGgleMaps', models.URLField(blank=True, max_length=2000, null=True)),
                ('Cidade', models.CharField(max_length=175)),
                ('Country', models.CharField(default='Brasil', max_length=100)),
                ('CEP', models.CharField(max_length=9)),
                ('Descricao', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('UF', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.ufestados')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_mn_Esquerdo', models.CharField(choices=[('1', 'Ativo'), ('0', 'Inativo')], default='1', max_length=1)),
                ('Endereco', models.CharField(max_length=200)),
                ('Bairro', models.CharField(max_length=125)),
                ('Cidade', models.CharField(max_length=175)),
                ('Country', models.CharField(default='Brasil', max_length=100)),
                ('CEP', models.CharField(max_length=15)),
                ('Celular', models.CharField(blank=True, max_length=11, null=True, verbose_name='Nº telefone celular')),
                ('TelFixo', models.CharField(blank=True, max_length=11, null=True, verbose_name='Nº telefone fixo')),
                ('RG', models.ImageField(upload_to='rgs')),
                ('CPF', models.CharField(max_length=14)),
                ('Foto', models.ImageField(upload_to='fotos_perfil')),
                ('Descricao', models.TextField(blank=True, null=True)),
                ('Empresa', models.CharField(default='SOME STRING', max_length=200)),
                ('Cargo', models.CharField(default='Indefinido', max_length=150)),
                ('token', models.CharField(default='SOME STRING', max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('UF', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.ufestados')),
            ],
        ),
    ]
